apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-demo-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-demo-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/sample-accelerators/tap-demo-app
      ref:
        branch: main
